### ISSUE TITLE
path-autocomplete does not work in css file

### ISSUE THREAD

**Issue by zbandhan** [ionutvmi/path-autocomplete#22]

**Comment by ionutvmi** [comment]
By default the autocomplete is triggered inside quotes.

You might want to enable the following option `path-autocomplete.triggerOutsideStrings` and see if that helps.

**Comment by juanda99** [comment]
It works ok with quotes, however when file get selected it doesn't put the extension:
<img width="693" alt="captura de pantalla 2017-08-29 a las 20 53 59" src="https://user-images.githubusercontent.com/2182923/29838770-677625da-8cfc-11e7-9e68-ff5b8bb5466b.png">
When selecting file, it would write "estilos/misestilos" instead of "estilos/misestilos.css"

**Comment by ionutvmi** [comment]
@juanda99 try to enable the setting `path-autocomplete.extensionOnImport`. 
By default it's false.
