### ISSUE TITLE
Use Auto-completion Outside String

### ISSUE THREAD

**Issue by W4RH4WK** [ionutvmi/path-autocomplete#8]
Is it possible to have auto-completion for paths outside of strings? I have to type `"`, use the auto-completion and then remove the `"` afterwards.

**Comment by ionutvmi** [comment]
I'm not sure how good that would work out considering it will get triggered when you do math expressions
`2 / 3`.

What type of files are you working on ? Maybe we can limit it for a specific scope.

**Comment by W4RH4WK** [comment]
I'd like to use this for various different purposes, and I have disabled the automatic triggering for completion anyway. I understand your urge to limit the scope as it can get quite annoying.

What do you think about adding a config setting for this. False by default, and if set to true, path auto-completion can be used within every context.

A different approach would be to have a dedicated shortcut for triggering path auto-completion, similar to VIM's `ctrl-x ctrl-f`. This would then trigger auto-completion wherever the cursor is located only showing paths. Yet I do not know whether this fine grained control is possible in VSCode.

**Comment by W4RH4WK** [comment]
Any updates?

**Comment by ionutvmi** [comment]
I looked at this a bit and limiting the scope is not the only problem here. The most tricky part is extracting the path that was already inserted by the user.

If we have something like `import aa from '/aa/bb/'` we know that the base path is `/aa/bb/` because of quotes. 
However if we extend it to work in any situation we could end up with a scenario like `open ~/settings/`. All the characters on that line are valid identifiers in a path. Because of this ambiguity we would end up with incorrect results most of the times. 

Currently the best we can get is that workaround with the quotes.

**Comment by W4RH4WK** [comment]
I see your point. I think it would be sufficient to extract the already inserted path by just matching the previous *WORD* (delimited by whitespace). Not only is this also the way it is implemented in Vim, but should also work in most cases as spaces are discourage anyway.

Yet I understand if you'd rather not implement a feature which only works in 9 of 10 use-cases. Although I'd appreciate adding it anyway and having to manually bind a shortcut to use it.
